quarkus:
  application:
    name: service-1
    version: 0.0.1
  log:
    level: INFO
    handler:
      console:
        request-handler:
          format: "%d{HH:mm:ss} %-5p request.id=%X{request.id} request.path=%X{request.path} [%c{2.}] (%t) %s%n"
    category:
      "com.acme":
        handlers: request-handler
        use-parent-handlers: false
  http:
    port: 8080
  ssl:
    native: true
  rest:
    path: /api
    jackson:
      optimization:
        enable-reflection-free-serializers: true
  smallrye-openapi:
    info-title: Service1 API
    info-description: Service1 API
    info-contact-email: danieldo@acme.com
    additional-docs-directory: openapi/
    store-schema-directory: .
  mongodb:
    uuid-representation: standard
  container-image:
    build: true
    push: true
    image: ghcr.io/danieldop/${quarkus.application.name}:${quarkus.application.version}

mp:
  messaging:
    outgoing:
      person-out:
        connector: smallrye-kafka
        topic: person

"%prod":
  quarkus:
    mongodb:
      database: demo
      connection-string: mongodb://quarkus:quarkus@127.0.0.1:27017/

"%qa":
  quarkus:
    mongodb:
      database: demo
      connection-string: mongodb://quarkus:quarkus@127.0.0.1:27017/
  kafka:
    bootstrap:
      servers: my-cluster-kafka-bootstrap:9092

"%dev":
  quarkus:
    log:
      level: INFO
      category:
        "con.acme":
          level: DEBUG
        "WebApplicationException":
          level: DEBUG
    smallrye-openapi:
      info-title: Service1 API (Development)
    live-reload:
      instrumentation: true
    mongodb:
      devservices:
        port: 27017
    observability:
      lgtm:
        grafana-port: 3001
        otel-grpc-port: 5317
        otel-http-port: 5318

"%test":
  quarkus:
    mongodb:
      devservices:
        port: 27017
